gui:
  nerdFontsVersion: 3
git:
  paging:
    colorArg: always
    pager: delta --dark --paging=never
os:
  editCommand: 'nvim'
  openCommand: 'nvim'
  editCommandTemplate: '{{editor}} {{filename}}'
  openCommandTemplate: '{{editor}} {{filename}}'
